#!/usr/bin/env python3
"""Phase 4 Batch A: Short UI labels"""
import csv, io

SRC = "/Users/michalhauzirek/Documents/Bludiste/data/translations.csv"

# lang order: en,cs,de,es,fr,pt,vi,tr,it,pl,sv,nb,nl,uk,fi,da,hu,ro,el,sk,he
NEW = {
"mp_host_new_game": ["Host new game","Spustit novou hru","Neues Spiel starten","Iniciar nueva partida","Démarrer une partie","Iniciar novo jogo","Tạo trò chơi mới","Yeni oyun başlat","Avvia nuova partita","Rozpocznij nową grę","Starta nytt spel","Start nytt spill","Nieuw spel starten","Розпочати нову гру","Aloita uusi peli","Start nyt spil","Új játék indítása","Pornește joc nou","Ξεκίνα νέο παιχνίδι","Spustiť novú hru","התחל משחק חדש"],
"mp_host_you": ["You:","Ty:","Du:","Tú:","Toi :","Você:","Bạn:","Sen:","Tu:","Ty:","Du:","Du:","Jij:","Ти:","Sinä:","Dig:","Te:","Tu:","Εσύ:","Ty:","אתה:"],
"mp_host_start_failed": ["Could not start host","Hru se nepodařilo spustit","Spiel konnte nicht gestartet werden","No se pudo iniciar la partida","Impossible de démarrer la partie","Não foi possível iniciar o jogo","Không thể bắt đầu trò chơi","Oyun başlatılamadı","Impossibile avviare la partita","Nie można uruchomić gry","Kunde inte starta spelet","Kunne ikke starte spillet","Kon het spel niet starten","Не вдалося запустити гру","Peliä ei voitu käynnistää","Kunne ikke starte spillet","A játék nem indítható","Jocul nu a putut fi pornit","Το παιχνίδι δεν ξεκίνησε","Hru sa nepodarilo spustiť","לא ניתן להתחיל את המשחק"],
"mp_host_player": ["Player","Hráč","Spieler","Jugador","Joueur","Jogador","Người chơi","Oyuncu","Giocatore","Gracz","Spelare","Spiller","Speler","Гравець","Pelaaja","Spiller","Játékos","Jucător","Παίκτης","Hráč","שחקן"],
"mp_join_discovery_title": ["Find Host","Najít hostitele","Host finden","Buscar partida","Trouver l'hôte","Encontrar anfitriã","Tìm máy chủ","Ev sahibi bul","Trova host","Znajdź hosta","Hitta värd","Finn vert","Vind host","Знайти хоста","Etsi isäntä","Find vært","Gazdát keresek","Găsește gazda","Βρες οικοδεσπότη","Nájsť hostiteľa","מצא מארח"],
"mp_join_discovery_scanning": ["Scanning local Wi-Fi","Prohledávám Wi-Fi síť","Suche im lokalen WLAN","Buscando en la red Wi-Fi","Recherche sur le Wi-Fi","Procurando na rede Wi-Fi","Đang quét Wi-Fi","Yerel Wi-Fi taranıyor","Ricerca nella rete Wi-Fi","Skanowanie sieci Wi-Fi","Söker på det lokala Wi-Fi","Søker på lokalt Wi-Fi","Lokaal Wi-Fi scannen","Сканування Wi-Fi мережі","Skannaan paikallista Wi-Fiä","Scanner lokalt Wi-Fi","Helyi Wi-Fi keresése","Scanează rețeaua Wi-Fi","Σάρωση τοπικού Wi-Fi","Prehľadávam Wi-Fi sieť","סורק רשת Wi-Fi מקומית"],
"mp_join_discovery_none": ["No hosts found yet","Zatím žádný host","Noch kein Host gefunden","Aún no hay partidas","Aucun hôte trouvé","Nenhum host encontrado","Chưa tìm thấy máy chủ","Henüz ev sahibi bulunamadı","Nessun host trovato","Nie znaleziono hosta","Ingen värd hittad","Ingen vert funnet","Nog geen host gevonden","Хостів ще не знайдено","Isäntiä ei löydy vielä","Ingen vært fundet endnu","Még nincs találat","Niciun host găsit","Δεν βρέθηκε κανείς","Zatiaľ žiadny hostiteľ","טרם נמצא מארח"],
"mp_join_discovery_found": ["Hosts found","Host nalezen","Host gefunden","Partida encontrada","Hôte trouvé","Host encontrado","Đã tìm thấy máy chủ","Ev sahibi bulundu","Host trovato","Znaleziono host","Värd hittad","Vert funnet","Host gevonden","Хост знайдено","Isäntä löydetty","Vært fundet","Találat!","Host găsit","Βρέθηκε!","Hostiteľ nájdený","נמצא מארח"],
"mp_join_discovery_error": ["Discovery failed","Hledání selhalo","Suche fehlgeschlagen","Error al buscar","Recherche échouée","Busca falhou","Tìm kiếm thất bại","Arama başarısız","Ricerca fallita","Wyszukiwanie nie powiodło się","Sökning misslyckades","Søk mislyktes","Zoeken mislukt","Пошук не вдався","Haku epäonnistui","Søgning mislykkedes","Keresési hiba","Căutare eșuată","Η αναζήτηση απέτυχε","Hľadanie zlyhalo","החיפוש נכשל"],
"mp_join_character": ["Character","Postava","Figur","Personaje","Personnage","Personagem","Nhân vật","Karakter","Personaggio","Postać","Karaktär","Karakter","Personage","Персонаж","Hahmo","Karakter","Karakter","Personaj","Χαρακτήρας","Postava","דמות"],
"mp_join_game": ["Join Game","Připojit se ke hře","Dem Spiel beitreten","Unirse a la partida","Rejoindre la partie","Entrar no jogo","Tham gia trò chơi","Oyuna katıl","Unisciti alla partita","Dołącz do gry","Gå med i spelet","Bli med i spillet","Doe mee aan het spel","Приєднатися до гри","Liity peliin","Deltag i spillet","Csatlakozás a játékhoz","Intră în joc","Μπες στο παιχνίδι","Pripojiť sa do hry","הצטרף למשחק"],
"mp_join_error_character": ["Select an available character","Vyber si dostupnou postavu","Wähle eine verfügbare Figur","Selecciona un personaje disponible","Choisis un personnage disponible","Escolha um personagem disponível","Chọn nhân vật có sẵn","Mevcut bir karakter seç","Scegli un personaggio disponibile","Wybierz dostępną postać","Välj en tillgänglig karaktär","Velg en tilgjengelig karakter","Kies een beschikbaar personage","Обери доступного персонажа","Valitse käytettävissä oleva hahmo","Vælg en tilgængelig karakter","Válassz szabad karaktert","Alege un personaj disponibil","Επίλεξε διαθέσιμο χαρακτήρα","Vyber si dostupnú postavu","בחר דמות זמינה"],
"mp_join_error_character_taken": ["Character is already taken","Tato postava je již obsazena","Diese Figur ist schon vergeben","Este personaje ya está ocupado","Ce personnage est déjà pris","Este personagem já está ocupado","Nhân vật này đã được chọn","Bu karakter zaten alındı","Questo personaggio è già preso","Ta postać jest już zajęta","Den karaktären är redan tagen","Den karakteren er allerede tatt","Dit personage is al bezet","Цей персонаж вже зайнятий","Tämä hahmo on jo otettu","Den karakter er allerede taget","Ez a karakter már foglalt","Personajul este deja ocupat","Αυτός ο χαρακτήρας είναι ήδη κατειλημμένος","Táto postava je už obsadená","הדמות הזו כבר תפוסה"],
"mp_join_error_connect": ["Could not connect to host","Nepodařilo se připojit","Verbindung fehlgeschlagen","No se pudo conectar","Connexion impossible","Não foi possível conectar","Không thể kết nối","Bağlantı kurulamadı","Impossibile connettersi","Nie udało się połączyć","Kunde inte ansluta","Kunne ikke koble til","Kan geen verbinding maken","Не вдалося під'єднатися","Yhteys epäonnistui","Forbindelsen mislykkedes","Csatlakozás sikertelen","Nu s-a putut conecta","Αδύνατη η σύνδεση","Nepodariło sa pripojiť","לא ניתן להתחבר"],
"mp_join_connecting": ["Connecting to host","Připojuji se...","Verbindung herstellen...","Conectando...","Connexion en cours...","Conectando...","Đang kết nối...","Bağlanılıyor...","Connessione in corso...","Łączenie...","Ansluter...","Kobler til...","Verbinden...","Підключення...","Yhdistetään...","Opretter forbindelse...","Csatlakozás...","Se conectează...","Σύνδεση...","Pripájam sa...","מתחבר..."],
"mp_join_host_unavailable": ["Host unavailable","Hostitel není dostupný","Host nicht verfügbar","Partida no disponible","Hôte indisponible","Host indisponível","Máy chủ không khả dụng","Ev sahibi mevcut değil","Host non disponibile","Host niedostępny","Värden är inte tillgänglig","Verten er ikke tilgjengelig","Host niet beschikbaar","Хост недоступний","Isäntä ei ole saatavilla","Vært ikke tilgængelig","A gazda nem elérhető","Gazda indisponibilă","Ο οικοδεσπότης δεν είναι διαθέσιμος","Hostiteľ nie je dostupný","המארח אינו זמין"],
"mp_join_remote_layout": ["Controller layout:","Rozvržení ovladače:","Controller-Layout:","Diseño del mando:","Disposition du contrôleur :","Layout do controle:","Bố cục điều khiển:","Kumanda düzeni:","Layout del controller:","Układ kontrolera:","Kontrollerlayout:","Kontrollerlayout:","Controller-indeling:","Розкладка контролера:","Ohjainasettelu:","Controller-layout:","Vezérlő elrendezése:","Aspect controler:","Διάταξη χειριστηρίου:","Rozloženie ovládača:","סידור שלט:"],
"mp_game_waiting": ["Waiting for session","Čekám na hru","Warte auf das Spiel","Esperando partida","En attente de session","Aguardando sessão","Đang chờ phiên chơi","Oturum bekleniyor","In attesa della sessione","Oczekiwanie na sesję","Väntar på session","Venter på økt","Wacht op sessie","Очікування сесії","Odotetaan istuntoa","Venter på session","Várom a játékot","Se așteaptă sesiunea","Αναμονή για παιχνίδι","Čakám na hru","ממתין לסשן"],
"mp_game_running": ["Multiplayer game running","Hra více hráčů probíhá","Mehrspielerspiel läuft","Partida multijugador en curso","Partie multijoueur en cours","Jogo multiplayer em andamento","Trò chơi nhiều người đang chạy","Çok oyunculu oyun devam ediyor","Partita multigiocatore in corso","Gra wieloosobowa trwa","Flerspelarspelet pågår","Flerspillerspill pågår","Meerdere spelersspel loopt","Багатокористувацька гра йде","Moninpeli käynnissä","Flerspillerspil kører","Többjátékos játék folyamatban","Joc multiplayer în desfășurare","Το παιχνίδι τρέχει","Hra viacerých hráčov prebieha","משחק מרובה שחקנים בהתנהלות"],
"mp_slot_waiting": ["Waiting...","Čekám...","Warte...","Esperando...","En attente...","Aguardando...","Đang chờ...","Bekleniyor...","In attesa...","Czekam...","Väntar...","Venter...","Wacht...","Очікування...","Odotetaan...","Venter...","Várok...","Se așteaptă...","Αναμονή...","Čakám...","ממתין..."],
"mp_slot_you": ["You","Ty","Du","Tú","Toi","Você","Bạn","Sen","Tu","Ty","Du","Du","Jij","Ти","Sinä","Dig","Te","Tu","Εσύ","Ty","אתה"],
"mp_slot_host": ["Host","Hostitel","Gastgeber","Anfitrión","Hôte","Anfitrião","Máy chủ","Ev sahibi","Ospite","Gospodarz","Värd","Vert","Host","Хост","Isäntä","Vært","Gazda","Gazdă","Οικοδεσπότης","Hostiteľ","מארח"],
"mp_waiting_for_host": ["Waiting for host to start the game.","Čekám, až hostitel spustí hru.","Warte darauf, dass der Gastgeber das Spiel startet.","Esperando que el anfitrión inicie la partida.","En attente du lancement par l'hôte.","Aguardando o anfitrião iniciar o jogo.","Đang chờ máy chủ bắt đầu trò chơi.","Ev sahibinin oyunu başlatması bekleniyor.","In attesa che l'ospite avvii la partita.","Czekam, aż gospodarz uruchomi grę.","Väntar på att värden startar spelet.","Venter på at verten starter spillet.","Wachten tot de host het spel start.","Очікую поки хост почне гру.","Odotetaan isäntää aloittamaan peli.","Venter på at værten starter spillet.","Várom, hogy a gazda elindítsa a játékot.","Se așteaptă ca gazda să înceapă jocul.","Αναμένω να ξεκινήσει ο οικοδεσπότης.","Čakám, kým hostiteľ spustí hru.","ממתין שהמארח יתחיל את המשחק."],
"mp_waiting_for_players": ["Waiting for players to join...","Čekám na hráče...","Warte auf Spieler...","Esperando jugadores...","En attente de joueurs...","Aguardando jogadores...","Đang chờ người chơi...","Oyuncular bekleniyor...","In attesa di giocatori...","Czekam na graczy...","Väntar på spelare...","Venter på spillere...","Wacht op spelers...","Очікування гравців...","Odotetaan pelaajia...","Venter på spillere...","Várok a játékosokra...","Se aşteaptă jucătorii...","Αναμονή παικτών...","Čakám na hráčov...","ממתין לשחקנים..."],
"mp_start_game_1": ["Start Game with 1 player","Spustit hru s 1 hráčem","Spiel mit 1 Spieler starten","Iniciar partida con 1 jugador","Démarrer avec 1 joueur","Iniciar com 1 jogador","Bắt đầu với 1 người","1 oyuncuyla başlat","Avvia con 1 giocatore","Rozpocznij z 1 graczem","Starta med 1 spelare","Start med 1 spiller","Start met 1 speler","Почати з 1 гравцем","Aloita 1 pelaajalla","Start med 1 spiller","Indítás 1 játékossal","Pornește cu 1 jucător","Έναρξη με 1 παίκτη","Spustiť hru s 1 hráčom","התחל עם שחקן 1"],
"mp_start_game_n": ["Start Game with %d players","Spustit hru s %d hráči","Spiel mit %d Spielern starten","Iniciar partida con %d jugadores","Démarrer avec %d joueurs","Iniciar com %d jogadores","Bắt đầu với %d người","​%d oyuncuyla başlat","Avvia con %d giocatori","Rozpocznij z %d graczami","Starta med %d spelare","Start med %d spillere","Start met %d spelers","Почати з %d гравцями","Aloita %d pelaajalla","Start med %d spillere","Indítás %d játékossal","Pornește cu %d jucători","Έναρξη με %d παίκτες","Spustiť hru s %d hráčmi","התחל עם %d שחקנים"],
"mp_how_to_join": ["How to Join","Jak se připojit","So wirst du Mitspieler","Cómo unirse","Comment rejoindre","Como entrar","Cách tham gia","Nasıl katılınır","Come partecipare","Jak dołączyć","Hur man går med","Slik blir du med","Hoe meedoen","Як приєднатися","Kuinka liittyä","Sådan deltager du","Csatlakozás módja","Cum să te alături","Πώς να μπεις","Ako sa pripojiť","כיצד להצטרף"],
"mp_slot_join_as": ["Join as %s","Připoj se jako %s","Beitreten als %s","Únete como %s","Rejoindre en tant que %s","Entrar como %s","Tham gia làm %s","%s olarak katıl","Unisciti come %s","Dołącz jako %s","Gå med som %s","Bli med som %s","Doe mee als %s","Приєднатися як %s","Liity %s-roolissa","Deltag som %s","Csatlakozz mint %s","Alătură-te ca %s","Συμμετοχή ως %s","Pripoj sa ako %s","הצטרף בתור %s"],
}

def patch(src, updates):
    with open(src, encoding="utf-8", newline="") as f:
        reader = csv.reader(f)
        rows = list(reader)
    header = rows[0]
    data = {r[0]: r for r in rows[1:] if r}

    count = 0
    for key, vals in updates.items():
        if len(vals) != len(header):
            print(f"SKIP {key}: expected {len(header)} cols, got {len(vals)}")
            continue
        if key in data:
            # only fill empty/English-placeholder cells
            for i, v in enumerate(vals):
                existing = data[key][i]
                if i == 0 or (existing.strip() == vals[0].strip() and i > 0):
                    data[key][i] = v
                elif existing.strip() == "":
                    data[key][i] = v
            count += 1
        else:
            print(f"KEY NOT FOUND: {key}")

    out_rows = [header] + list(data.values())
    with open(src, "w", encoding="utf-8", newline="\n") as f:
        csv.writer(f).writerows(out_rows)
    print(f"Batch A: patched {count} keys.")

patch(SRC, NEW)
